"""Hand-picked edge-case sequences for ANARCI ground-truth.
H/K/L pulled from antibody_sequences.fasta (real IMGT-numbered examples).
TCR alpha/beta are well-known published variable domains (recall-sourced),
verified below to number as A/B chains.
12e8 H and L from the bundled 12e8.fasta. scFv = VH+linker+VL (from API example).
"""

# Real examples from antibody_sequences.fasta
VH_1mhp = "EVQLVESGGGLVQPGGSLRLSCAASGFTFSRYTMSWVRQAPGKGLEWVATISGGGHTYYLDSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCTRGFGDGGYFDVWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPK"
VK_1mhp = "IQLTQSPSSLSASVGDRVTITCSASSSVNHMFWYQQKPGKAPKPWIYLTSNLASGVPSRFSGSGSGTDYTLTISSLQPEDFATYYCQQWSGNPWTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
VL_2fl5 = "SYELKQPPSVSVSPGQTARITCSGDVLPKKYAYWYQERSGQAPVLVVYEDSGRPSEIPERFSGSSSGTKATLTISGAQVEDEADYYCYSDISNGYPLFGGGTKLSVGQPKAAPSVTLFPPSSEELQANKATLVCLISDFYPGAVTVAWKADSSPIKAGVETTTPSKQSNNKYAASSYLSLTPEQWKSHRSYSCQVTHEGSTVEKTVAPT"

# 12e8 from bundled fasta
H_12e8 = "EVQLQQSGAEVVRSGASVKLSCTASGFNIKDYYIHWVKQRPEKGLEWIGWIDPEIGDTEYVPKFQGKATMTADTSSNTAYLQLSSLTSEDTAVYYCNAGHDYDRGRFPYWGQGTLVTVSAAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPRD"
L_12e8 = "DIVMTQSQKFMSTSVGDRVSITCKASQNVGTAVAWYQQKPGQSPKLMIYSASNRYTGVPDRFTGSGSGTDFTLTISNMQSEDLADYFCQQYSSYPLTFGAGTKLELKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSATDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC"

# scFv VH+(G4S)x4+VL+His  (from ANARCI API example) -> multi-domain
scfv = "DIQMTQSPSSLSASVGDRVTITCRTSGNIHNYLTWYQQKPGKAPQLLIYNAKTLADGVPSRFSGSGSGTQFTLTISSLQPEDFANYYCQHFWSLPFTFGQGTKVEIKRTGGGGSGGGGSGGGGSGGGGSEVQLVESGGGLVQPGGSLRLSCAASGFDFSRYDMSWVRQAPGKRLEWVAYISSGGGSTYFPDTVKGRFTISRDNAKNTLYLQMNSLRAEDTAVYYCARQNKKLTWFDYWGQGTLVTVSSHHHHHH"

# Very long CDR3 heavy chain (bovine ultralong-style synthetic: insert long CDRH3)
long_cdr3 = "EVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCARDRGYTYGNYYYYYGMDVWGQGTTVTVSS"

# Too-short fragment (<70 aa): truncated VH framework1+CDR1 only
too_short = "EVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGK"

# Lysozyme negative control (non-antibody)
lysozyme = "KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL"

# TCR alpha and beta variable domains (recall-sourced reference sequences; verified at runtime)
# Human TCR alpha V-region (A6 TCR-like)
tcr_alpha = "QKEVEQNSGPLSVPEGAIASLNCTYSDRGSQSFFWYRQYSGKSPELIMSIYSNGDKEDGRFTAQLNKASQYVSLLIRDSQPSDSATYLCAVTTDSWGKLQFGAGTQVVVTP"
# Human TCR beta V-region (A6 TCR-like)
tcr_beta = "NAGVTQTPKFQVLKTGQSMTLQCAQDMNHEYMSWYRQDPGMGLRLIHYSVGAGITDQGEVPNGYNVSRSTTEDFPLRLLSAAPSQTSVYFCASRPGLAGGRPEQYFGPGTRLTVT"

EDGE_CASES = [
    ("edge_VH_1mhp_heavy", VH_1mhp),
    ("edge_VK_1mhp_kappa", VK_1mhp),
    ("edge_VL_2fl5_lambda", VL_2fl5),
    ("edge_TCR_alpha", tcr_alpha),
    ("edge_TCR_beta", tcr_beta),
    ("edge_scFv_VHVL", scfv),
    ("edge_long_cdr3", long_cdr3),
    ("edge_too_short", too_short),
    ("edge_lysozyme_negctrl", lysozyme),
    ("edge_12e8_H", H_12e8),
    ("edge_12e8_L", L_12e8),
]

if __name__ == "__main__":
    from anarci import run_anarci
    _, numbered, details, hits = run_anarci(EDGE_CASES, scheme="imgt", ncpu=1,
                                            assign_germline=True,
                                            allowed_species=['human','mouse','rat','rabbit','rhesus','pig','alpaca'])
    for (name, s), det in zip(EDGE_CASES, details):
        if det is None:
            print(f"{name}\tNONE")
        else:
            cts = [d.get("chain_type") for d in det]
            sp = [d.get("species") for d in det]
            print(f"{name}\tdomains={len(det)}\tchain_type={cts}\tspecies={sp}")
