#!/usr/bin/env python
"""Emit the two large numbering constants (alphabet, blosum62) as a Rust source file,
straight from the reference package so there is zero hand-transcription risk.

  python scripts/gen_constants.py
"""
import os
from anarci import schemes as S

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
out = os.path.join(ROOT, "crates", "anarci-core", "src", "generated_constants.rs")

lines = []
lines.append("// @generated by scripts/gen_constants.py from reference ANARCI schemes.py — DO NOT EDIT.")
lines.append("// alphabet: the 53-entry insertion alphabet (A..Z, AA..ZZ, then a single space).")
lines.append("// Python `alphabet[i]`: i==-1 -> ALPHABET[52] (\" \"); i in 0..=51 -> A..ZZ.")
lines.append("")
assert len(S.alphabet) == 53
quoted = ", ".join('"%s"' % a for a in S.alphabet)
lines.append("pub static ALPHABET: [&str; 53] = [%s];" % quoted)
lines.append("")
lines.append("// BLOSUM62 exactly as stored in schemes.py (asymmetric: only one (a,b) direction).")
lines.append("// Used solely by wolfguy CDRL1 canonical-class scoring, which tries (a,b) then (b,a).")
lines.append("pub static BLOSUM62_RAW: &[(u8, u8, i32)] = &[")
items = list(S.blosum62.items())
assert len(items) == 276, len(items)
for (a, b), v in items:
    lines.append("    (b'%s', b'%s', %d)," % (a, b, v))
lines.append("];")
lines.append("")

with open(out, "w") as f:
    f.write("\n".join(lines))
print("wrote", out, "(", len(items), "blosum entries )")
