//! Raw FFI bindings to a vendored, statically linked HMMER 3.4 + Easel.
//!
//! Generated by bindgen at build time (see `build.rs`). All items are the C
//! API verbatim; safety and choreography live in the `anarci-hmm` crate.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
